# Tên của workflow, sẽ hiển thị trên tab Actions
name: Python Code Quality Check

# Khi nào workflow sẽ chạy
on:
  push:
    branches: [ "main" ] # Chạy khi có code mới được đẩy lên nhánh main
  pull_request:
    branches: [ "main" ] # Chạy khi có một pull request được tạo vào nhánh main

jobs:
  build:
    # Môi trường để chạy, "ubuntu-latest" là lựa chọn phổ biến và ổn định
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy mã nguồn của bạn từ repository về máy ảo
      - name: Check out repository code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt phiên bản Python mà chúng ta đang dùng
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Đảm bảo khớp với môi trường của bạn

      # Bước 3: Cài đặt các thư viện cần thiết
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Bước 4: Chạy Pylint để kiểm tra chất lượng code
      - name: Lint with Pylint
        run: |
          pylint $(git ls-files '*.py')
